# -*- coding: utf-8 -*-
"""Scratch2Py Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXGayIWNPnjVk3VdglEmSeFxWXJvkG_H

## Program-01
"""

# 使用者輸入姓名後，電腦回應使用者
name = input('你的名字是？')
print(f'Hi, {name}！ 一起來當py郎~~')

"""| 命名類型   | 命名規則                             |
|:----------:|:------------------------------------:|
| 變數、函式       | 使用小寫字母，單詞之間用底線分隔 (例如 `my_variable`) |
| 常數       | 使用全大寫字母，單詞之間用底線分隔 (例如 `MY_CONSTANT`) |
| 類別       | 使用駝峰式命名法 (CamelCase) (例如 `MyClass`) |
| 模組、套件       | 使用小寫字母，單詞之間用底線分隔 (例如 `my_module`) |

**底線開頭或結尾的名稱在python中有特殊用途，應避開這些特殊命名方式。**
"""

# 列出keyword, keyword不能當作變數名稱
import keyword
print(keyword.kwlist)

# 查詢函式print用法
help(print)

"""| 跳脫序列(Escape Sequence) | 說明             |
|:---------------:|:----------------:|
| `\\`           | 反斜線           |
| `\'`           | 單引號           |
| `\"`           | 雙引號           |
| `\n`           | 換行             |
| `\t`           | 水平製表符(Tab)       |
| `\r`           | 回車             |
| `\b`           | 退格             |
| `\f`           | 垂直製表符       |
| `\a`           | 鈴聲             |
| `\v`           | 垂直製表符       |
| `\ooo`         | 八進位數字      |
| `\xhh`         | 十六進位數字    |

## Program-02

| Operator | 說明                     |
|:--------:|:------------------------:|
| `+`      | 加法                     |
| `-`      | 減法                     |
| `*`      | 乘法                     |
| `/`      | 除法                     |
| `//`     | 整數除法（向下取整）     |
| `%`      | 取餘數                   |
| `**`     | 指數（冪）               |
"""

num_1 = float(input('輸入第一個數字：'))
num_2 = float(input('輸入第二個數字：'))
print(f'{num_1} + {num_2} = {num_1 + num_2}')
print(f'{num_1} - {num_2} = {num_1 - num_2}')
print(f'{num_1} * {num_2} = {num_1 * num_2}')
print(f'{num_1} / {num_2} = {num_1 / num_2}')

"""| 格式規範               | 說明                               |
|----------------------|----------------------------------|
| **format_spec**      |[**align**][**+**][**#**][**0**][**width**][**,**][**.precision**][**type**] |
| **align**            | `<` (靠左)、`^` (置中)、`>` (靠右) |
| **+**                | 正、負號                           |
| **#**                | `0b` (2進位)、`0o` (8進位)、`0x` (16進位) |
| **0**                | 數字左邊空欄位補 0                 |
| **width**            | 字元寬度                           |
| **,**                | 千分位符號                         |
| **.precision**       | 小數點下位數                       |
| **type**             | `s` (字串)、`d` (整數)、`f` (浮點數)、`b` (2進位)、`o` (8進位)、`x` (16進位) |
"""

a = float(input('輸入第一個數字：'))
b = float(input('輸入第二個數字：'))
if a > b:
    print(f'{a} > {b}')
elif a < b:
    print(f'{a} < {b}')
else:
    print(f'{a} = {b}')



"""| Operator | 說明                     |
|:--------:|:------------------------:|
| `==`     | 等於                   |
| `!=`     | 不等於                   |
| `>`      | 大於                     |
| `<`      | 小於                     |
| `>=`     | 大於或等於               |
| `<=`     | 小於或等於               |
"""

def http_error(status):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case _:
            return "Something's wrong with the internet"

http_error(418)

grade = 30
print('及格' if grade >= 60 else '不及格')

